### ISSUE TITLE
After refactoring checklist

### ISSUE THREAD

**Issue by Premwoik** [Premwoik/SmartHome#27]
### Pure core functionality:

1. Device

- [ ]  Port

- [ ] Dimmer

- [ ] Light

- [ ] Sunblind

- [ ] RfButton

- [ ] Task

- [ ] Item

2. Tasks

- [ ] Action up

- [ ] Action down

- [ ] Hearthbeat

- [ ] Read inputs

- [ ] Read outputs

- [ ] Read temp

- [ ] Read energy

- [ ] Clean logs

- [ ] Group data hourly

- [ ] Monitor device

3. Actions

- [ ] Auto lights

- [ ] Close sunblinds

- [ ] Tick Dimmer Controller

- [ ] Toggle item group
